// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_categories.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeedCategory = `-- name: CreateFeedCategory :exec
INSERT INTO feed_categories (feed_id, category_id)
VALUES ($1, $2)
ON CONFLICT (feed_id, category_id) DO NOTHING
`

type CreateFeedCategoryParams struct {
	FeedID     uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) CreateFeedCategory(ctx context.Context, arg CreateFeedCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createFeedCategory, arg.FeedID, arg.CategoryID)
	return err
}

const getCategoriesForFeed = `-- name: GetCategoriesForFeed :many
SELECT c.id, c.name, c.slug, c.created_at
FROM categories c
JOIN feed_categories fc ON fc.category_id = c.id
WHERE fc.feed_id = $1
ORDER BY c.name ASC
`

func (q *Queries) GetCategoriesForFeed(ctx context.Context, feedID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesForFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
