// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_categories.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserCategory = `-- name: CreateUserCategory :exec
INSERT INTO user_categories (user_id, category_id)
VALUES ($1, $2)
ON CONFLICT (user_id, category_id) DO NOTHING
`

type CreateUserCategoryParams struct {
	UserID     uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) CreateUserCategory(ctx context.Context, arg CreateUserCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createUserCategory, arg.UserID, arg.CategoryID)
	return err
}

const deleteUserCategories = `-- name: DeleteUserCategories :exec
DELETE FROM user_categories
WHERE user_id = $1
`

func (q *Queries) DeleteUserCategories(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserCategories, userID)
	return err
}

const getCategoriesForUser = `-- name: GetCategoriesForUser :many
SELECT c.id, c.name, c.slug, c.created_at
FROM categories c
JOIN user_categories uc ON uc.category_id = c.id
WHERE uc.user_id = $1
ORDER BY c.name ASC
`

func (q *Queries) GetCategoriesForUser(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
