// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/google/uuid"
	"github.com/peterintech/briefed/components"
	webtypes "github.com/peterintech/briefed/types"
)

func Login(data webtypes.LoginData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"mx-auto grid min-h-[calc(100vh-5rem)] max-w-[96rem] px-5 py-6 lg:grid-cols-[minmax(0,1.02fr)_minmax(28rem,0.98fr)] lg:px-8 lg:py-8\"><section class=\"relative hidden min-h-[42rem] overflow-hidden rounded-l-overlay bg-forest-900 lg:block\"><img src=\"/public/login.png\" alt=\"login\" class=\"absolute inset-0 h-full w-full object-cover\"><div class=\"absolute inset-0 bg-ink/40\"></div><a href=\"/\" class=\"absolute left-10 top-9 inline-flex items-center gap-3\"><div class=\"bg-paper-raised py-2 px-3 rounded-full\"><img src=\"public/logo.png\" alt=\"Briefed\" width=\"100px\" height=\"30px\"></div></a><div class=\"absolute inset-x-10 bottom-10 max-w-lg text-paper-raised xl:inset-x-12 xl:bottom-12\"><p class=\"text-xs font-bold uppercase tracking-[0.12em] text-paper-raised/75\">Your daily reading, refined</p><h1 class=\"mt-4 text-5xl font-bold leading-[0.98] tracking-[-0.055em] xl:text-6xl\">Pick up where your curiosity left off.</h1><p class=\"mt-5 max-w-[44ch] text-base leading-7 text-paper-raised/80\">Return to the latest stories from the sources and subjects you chose.</p></div></section><section class=\"flex min-h-[36rem] items-center rounded-overlay border border-rule bg-paper-raised px-6 py-12 shadow-overlay sm:px-10 lg:min-h-[42rem] lg:rounded-l-none lg:border-l-0 lg:px-14 lg:shadow-none xl:px-20\"><div class=\"mx-auto w-full max-w-md\"><p class=\"text-xs font-bold uppercase tracking-[0.1em] text-forest-800\">Welcome back</p><h2 class=\"mt-3 text-4xl font-bold tracking-[-0.045em] text-ink\">Log in to Briefed</h2><p class=\"mt-3 text-sm leading-6 text-muted\">Enter your details to return to your personalized feed.</p><form method=\"post\" action=\"/auth/login\" hx-post=\"/auth/login\" hx-target=\"#login-error\" hx-swap=\"innerHTML\" class=\"mt-8 space-y-5\"><div id=\"login-error\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.Error != "" {
				templ_7745c5c3_Err = components.InlineError(data.Error).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.TextField("email", "Email", "you@example.com", data.Email, "email", "email").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.TextField("password", "Password", "Your password", "", "password", "current-password").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<button type=\"submit\" class=\"inline-flex w-full items-center justify-center rounded-full bg-forest-900 px-6 py-3.5 text-sm font-semibold text-paper-raised transition-colors hover:bg-forest-800\">Log in</button></form><p class=\"mt-7 text-center text-sm text-muted\">New here? <a href=\"/\" class=\"font-semibold text-forest-800 hover:underline\">Personalize your feed</a></p></div></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.OnboardingModal(webtypes.InterestStepData{Categories: data.Categories, Selected: map[uuid.UUID]bool{}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Page("Log in · Briefed", nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
