// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/google/uuid"
	"github.com/peterintech/briefed/components"
	webtypes "github.com/peterintech/briefed/types"
)

func Login(data webtypes.LoginData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"mx-auto grid min-h-[calc(100vh-5rem)] max-w-[96rem] items-center px-5 py-14 lg:grid-cols-2 lg:px-8\"><section class=\"hidden max-w-xl lg:block\"><p class=\"text-xs font-bold uppercase tracking-[0.1em] text-forest-800\">Welcome back</p><h1 class=\"mt-4 text-6xl font-bold leading-[0.98] tracking-[-0.055em] text-ink\">Your reading list, right where you left it.</h1><p class=\"mt-6 max-w-[48ch] text-base leading-7 text-muted\">Sign in to see the newest stories from the sources you follow.</p></section><section class=\"mx-auto w-full max-w-md rounded-overlay border border-rule bg-paper-raised p-7 shadow-overlay sm:p-9\"><h1 class=\"text-3xl font-bold tracking-[-0.04em] text-ink lg:hidden\">Log in to Briefed</h1><form method=\"post\" action=\"/auth/login\" hx-post=\"/auth/login\" hx-target=\"#login-error\" hx-swap=\"innerHTML\" class=\"mt-6 space-y-5 lg:mt-0\"><div id=\"login-error\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.Error != "" {
				templ_7745c5c3_Err = components.InlineError(data.Error).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.TextField("email", "Email", "you@example.com", data.Email, "email", "email").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.TextField("password", "Password", "Your password", "", "password", "current-password").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<button type=\"submit\" class=\"inline-flex w-full items-center justify-center rounded-full bg-forest-900 px-6 py-3.5 text-sm font-semibold text-paper-raised hover:bg-forest-800\">Log in</button></form><p class=\"mt-6 text-center text-sm text-muted\">New here? <a href=\"/\" class=\"font-semibold text-forest-800 hover:underline\">Personalize your feed</a></p></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.OnboardingModal(webtypes.InterestStepData{Categories: data.Categories, Selected: map[uuid.UUID]bool{}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Page("Log in · Briefed", nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
