// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import webtypes "github.com/peterintech/briefed/types"

func FeedContributionDrawer(data webtypes.FeedContributionData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"feed-contribution-overlay\" data-drawer-overlay class=\"fixed inset-0 z-50\"><button type=\"button\" data-action=\"close-drawer\" aria-label=\"Close add feed\" class=\"drawer-backdrop absolute inset-0 bg-ink/35\" data-open=\"false\"></button><aside class=\"drawer-panel absolute inset-y-0 right-0 flex w-full max-w-[27.5rem] flex-col border-l border-rule bg-paper-raised shadow-overlay\" data-open=\"false\" aria-labelledby=\"feed-contribution-title\"><header class=\"flex items-start justify-between gap-5 border-b border-rule px-6 py-6\"><div><p class=\"text-xs font-bold uppercase tracking-[0.1em] text-forest-800\">Shared sources</p><h2 id=\"feed-contribution-title\" class=\"mt-2 text-3xl font-bold tracking-[-0.04em] text-ink\">Add an RSS feed</h2><p class=\"mt-2 text-sm leading-6 text-muted\">Paste the direct RSS or Atom URL. Once validated, the source becomes available to every Briefed reader.</p></div><button type=\"button\" data-action=\"close-drawer\" aria-label=\"Close\" class=\"grid size-10 shrink-0 place-items-center rounded-full text-muted hover:bg-paper hover:text-ink\"><span aria-hidden=\"true\" class=\"text-2xl\">×</span></button></header><div id=\"feed-drawer-body\" class=\"min-h-0 flex-1 overflow-y-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = FeedContributionForm(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></aside></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func FeedContributionForm(data webtypes.FeedContributionData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<form hx-post=\"/partials/feeds\" hx-target=\"#feed-drawer-body\" hx-swap=\"innerHTML\" hx-disabled-elt=\"#feed-submit\" class=\"flex min-h-full flex-col\"><div class=\"flex-1 px-6 py-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.Error != "" {
			templ_7745c5c3_Err = InlineError(data.Error).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<label class=\"block\"><span class=\"mb-2 block text-sm font-semibold text-ink\">Feed URL</span> <input data-drawer-focus type=\"url\" name=\"url\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(data.URL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/feed_contribution.templ`, Line: 32, Col: 67}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" placeholder=\"https://publisher.com/feed.xml\" autocomplete=\"url\" required autofocus class=\"w-full rounded-control border border-rule bg-paper px-4 py-3 text-sm text-ink placeholder:text-muted focus:border-forest-800\"></label><p class=\"mt-2 text-xs leading-5 text-muted\">Use the feed URL itself, not the publisher's homepage.</p><fieldset class=\"mt-8\"><legend class=\"text-xs font-bold uppercase tracking-[0.09em] text-ink\">Where does it belong?</legend><p class=\"mt-2 text-sm leading-6 text-muted\">Choose every category that fits. At least one is required.</p><div class=\"mt-4 flex flex-wrap gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, category := range data.Categories {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<label class=\"feed-category-choice\"><input class=\"peer sr-only\" type=\"checkbox\" name=\"category_ids\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(category.ID.String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/feed_contribution.templ`, Line: 41, Col: 99}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if selected(data.Selected, category.ID) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " checked")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "> <span class=\"inline-flex cursor-pointer items-center gap-2 rounded-full border border-rule px-4 py-2 text-sm font-semibold text-ink hover:border-forest-700 peer-checked:border-forest-800 peer-checked:bg-forest-50 peer-checked:text-forest-900 peer-focus-visible:ring-2 peer-focus-visible:ring-forest-800\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(category.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/feed_contribution.templ`, Line: 42, Col: 326}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " <span class=\"choice-plus\" aria-hidden=\"true\">+</span><span class=\"choice-check\" aria-hidden=\"true\">✓</span></span></label>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div></fieldset><div class=\"mt-8 border-t border-rule pt-5 text-xs leading-5 text-muted\"><p><span class=\"font-semibold text-ink\">What happens next:</span> Briefed fetches the URL, confirms it is RSS or Atom, extracts its title, publishes it globally, and follows it for you.</p></div></div><footer class=\"flex items-center justify-end gap-3 border-t border-rule px-6 py-5\"><button type=\"button\" data-action=\"close-drawer\" class=\"rounded-control px-5 py-3 text-sm font-semibold text-muted hover:text-ink\">Cancel</button> <button id=\"feed-submit\" type=\"submit\" class=\"rounded-full bg-forest-900 px-6 py-3 w-fit text-sm font-semibold text-paper-raised hover:bg-forest-800 disabled:cursor-wait disabled:opacity-60\"><span class=\"htmx-indicator mr-2\">Checking…</span><span class=\"[.htmx-request_&]:hidden\">Add feed</span></button></footer></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func FeedContributionSuccess(data webtypes.FeedContributionSuccess) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"flex min-h-full flex-col\"><div class=\"flex flex-1 flex-col justify-center px-6 py-10\"><div class=\"grid size-12 place-items-center rounded-full bg-forest-50 text-xl font-bold text-forest-900\" aria-hidden=\"true\">✓</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.Created {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<p class=\"mt-6 text-xs font-bold uppercase tracking-[0.09em] text-forest-800\">Source published</p><h3 class=\"mt-2 text-2xl font-bold tracking-[-0.035em] text-ink\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(data.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/feed_contribution.templ`, Line: 66, Col: 80}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, " is now on Briefed</h3><p class=\"mt-3 text-sm leading-6 text-muted\">You are following it, and other readers can now discover it through the categories you selected. Articles will appear after the scraper's next fetch.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<p class=\"mt-6 text-xs font-bold uppercase tracking-[0.09em] text-forest-800\">Already on Briefed</p><h3 class=\"mt-2 text-2xl font-bold tracking-[-0.035em] text-ink\">You now follow ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(data.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/feed_contribution.templ`, Line: 70, Col: 95}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</h3><p class=\"mt-3 text-sm leading-6 text-muted\">The source was already public, so we added it directly to your followed feeds.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 templ.SafeURL
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(data.URL))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/feed_contribution.templ`, Line: 73, Col: 36}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "\" target=\"_blank\" rel=\"noreferrer\" class=\"mt-5 truncate text-sm font-medium text-forest-800 hover:underline\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(data.URL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/feed_contribution.templ`, Line: 73, Col: 156}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</a></div><footer class=\"flex items-center justify-end gap-3 border-t border-rule px-6 py-5\"><button type=\"button\" hx-get=\"/partials/feeds/new\" hx-target=\"#overlay-root\" hx-swap=\"innerHTML\" class=\"rounded-control px-5 py-3 text-sm font-semibold text-muted hover:text-ink\">Add another</button> <button type=\"button\" data-action=\"close-drawer\" class=\"rounded-full bg-forest-900 px-6 py-3 text-sm font-semibold text-paper-raised hover:bg-forest-800\">Done</button></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
