// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import webtypes "github.com/peterintech/briefed/types"

func Header(viewer *webtypes.Viewer) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"border-b border-rule bg-paper\"><div class=\"mx-auto flex max-w-[96rem] items-center gap-5 px-5 py-5 lg:px-8\"><a href=\"/\" class=\"shrink-0 text-2xl font-bold tracking-[-0.04em] text-ink\">Briefed</a><div class=\"ml-auto flex items-center gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if viewer == nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"/login\" class=\"rounded-control px-4 py-2 text-sm font-semibold text-ink transition-colors hover:bg-paper-raised\">Log in</a> <button type=\"button\" data-action=\"open-onboarding\" class=\"rounded-full bg-forest-900 px-5 py-2.5 text-sm font-semibold text-paper-raised transition-colors hover:bg-forest-800\">Personalize</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span class=\"hidden text-sm text-muted sm:inline\">Hi, ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(viewer.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/layout.templ`, Line: 18, Col: 72}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span> <button type=\"button\" data-drawer-trigger hx-get=\"/partials/preferences\" hx-target=\"#overlay-root\" hx-swap=\"innerHTML\" class=\"rounded-full bg-forest-900 px-5 py-2.5 text-sm font-semibold text-paper-raised transition-colors hover:bg-forest-800\"><span class=\"sm:hidden\">Tune</span><span class=\"hidden sm:inline\">Personalize</span></button><form method=\"post\" action=\"/auth/logout\" hx-post=\"/auth/logout\" hx-swap=\"none\"><button type=\"submit\" class=\"rounded-control px-3 py-2 text-sm font-semibold text-muted transition-colors hover:text-ink\"><span class=\"hidden md:inline\">Log out</span><span class=\"md:hidden\">Out</span></button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
